# Copyright 2025-2026, Euro NCAP IVZW
# Created by IVEX NV (https://ivex.ai)
#
# Licensed under the Apache License 2.0.
# See http://www.apache.org/licenses/LICENSE-2.0 for details.

from typing import Dict
import copy
import pandas as pd
from euroncap_rating_2026 import common
from euroncap_rating_2026.safe_driving import data_model
from euroncap_rating_2026.crash_avoidance import matrix_processing
from euroncap_rating_2026.crash_avoidance import data_model as ca_data_model
from euroncap_rating_2026.crash_avoidance import test_info as ca_test_info
import logging
import random
import numpy as np
import re


logger = logging.getLogger(__name__)

VRU_LONGITUDINAL_SCENARIOS = {"CPLA", "CBLA"}
VRU_GREEN_V_REDUCTION_THRESHOLD = 30.0
# Speed-dependent green criterion for non-VRU scenarios: v_VUT - v_target - 2.
GREEN_V_REDUCTION_OFFSET = 2.0
# v_reduction above this earns the half (orange) score in every scenario.
ORANGE_V_REDUCTION_THRESHOLD = 15.0

CUT_OUT_SCENARIOS = {"CCR cut-out", "CMR cut-out"}


def get_green_v_reduction_threshold(
    scenario: str, v_scenario: int, v_target: int
) -> float:
    """Green-result threshold for v_reduction (km/h).

    Car-to-VRU - Longitudinal uses a fixed 30 km/h threshold.

    Cut-out is measured against the lead vehicle's (SOV) speed, which the
    protocol table records in the "Target speed" column: the VUT follows the
    SOV with ACC engaged, so it enters the conflict at the SOV's speed rather
    than at its own ACC set speed (the "VUT speed" column), and the SOV then
    cuts out to reveal a standstill GVT/EMT -- the collision target, at 0. So
    the speed to shed is the SOV's: v_SOV - 2, i.e. 48 and 68 km/h. Confirmed
    empirically: a VUT trailing the SOV enters the 90 km/h point's window at
    roughly the SOV's 70 km/h, so a v_VUT - 2 criterion would demand an
    88 km/h reduction from a vehicle travelling 70 and make that test point
    unwinnable.

    Every other scenario keeps the speed-dependent v_VUT - v_target - 2
    criterion. Cut-*in* is deliberately not included: there the target really
    is the collision target, and the VUT does travel at its own set speed.

    A cut-out row whose "Target speed" is 0 or blank comes from a template
    generated by a superseded library revision (before 5.4.6), which put the SOV
    speed in the "VUT speed" column and 0 in "Target speed". Such a row falls
    back to the "VUT speed" column -- which is where those sheets keep the SOV
    speed, so they keep scoring exactly as they do today, and a -2 threshold
    (which would score every measured reduction green) is impossible.
    consistency.find_prediction_inconsistencies reports those sheets so they
    get replaced rather than quietly tolerated.
    """
    if scenario in VRU_LONGITUDINAL_SCENARIOS:
        return VRU_GREEN_V_REDUCTION_THRESHOLD

    if scenario in CUT_OUT_SCENARIOS:
        v_sov = v_target
        if not v_sov:
            v_sov = v_scenario
            logger.warning(
                f"Cut-out row for '{scenario}' has no target speed -- this template "
                f"was generated by a library revision older than 5.4.6; scoring against the VUT speed "
                f"column ({v_sov} km/h)."
            )
        return float(v_sov - GREEN_V_REDUCTION_OFFSET)

    return float(v_scenario - v_target - GREEN_V_REDUCTION_OFFSET)


def get_category_for_scenario(scenario: str) -> str:
    if scenario in [
        "CCRs straight",
        "CCRs curved",
        "CCRm",
        "CCRb",
    ]:
        return "Car-to-Car - Longitudinal"
    elif scenario in ["CCR cut-in", "CCR cut-out"]:
        return "Car-to-Car - Cut-in / Cut-out"
    elif scenario in [
        "CMRs straight",
        "CMRs curved",
        "CMRm",
        "CMRb",
    ]:
        return "Car-to-Motorcyclist - Longitudinal"
    elif scenario in ["CMR cut-in", "CMR cut-out"]:
        return "Car-to-Motorcyclist - Cut-in / Cut-out"
    elif scenario in ["CPLA", "CBLA"]:
        return "Car-to-VRU - Longitudinal"
    else:
        return "Unknown"


def update_scenario_scores_autoresume_value(
    scenario_scores_df: pd.DataFrame,
    autoresume_value: str,
) -> pd.DataFrame:
    if scenario_scores_df.empty:
        logger.warning("Scenario Scores sheet is missing or empty.")
        return scenario_scores_df

    if autoresume_value is None:
        logger.warning("Auto-resume value not found.")
        return scenario_scores_df

    category_col = scenario_scores_df["Category"].fillna("").astype(str)

    mask = category_col.str.strip().str.lower() == "auto-resume"
    indices = scenario_scores_df.index[mask].tolist()

    if not indices:
        logger.warning(
            "No row with Category 'Auto-resume' found in Scenario Scores sheet."
        )
        return scenario_scores_df

    insert_idx = indices[0]
    if insert_idx >= len(scenario_scores_df):
        logger.warning(
            "No blank row found after 'Auto-resume' in Scenario Scores sheet."
        )
        return scenario_scores_df

    scenario_scores_df.loc[insert_idx, "Scenario"] = str(autoresume_value).strip()

    return scenario_scores_df


def _attributes_match(tp_attrs: dict, input_attrs: dict) -> bool:
    """Alias- and format-tolerant matching shared with crash_avoidance:
    resolves key aliases ("Impact location" vs "Impact Location") and
    normalizes impact-location values ("0.5" vs "50%") so an
    input_selected_points payload with a different spelling cannot silently
    match the wrong column."""
    return ca_test_info.attributes_match(tp_attrs, input_attrs)


def _select_points_from_input(
    candidate_points: list, requested_points: list, scenario_name: str
) -> list:
    selected_points = []

    for input_attrs in requested_points:
        matched_point = None
        for test_point in candidate_points:
            if _attributes_match(test_point.attributes, input_attrs):
                matched_point = copy.copy(test_point)
                matched_point.attributes = dict(test_point.attributes)
                break

        if matched_point is None:
            logger.warning(
                "[ACC %s] No TestPoint found matching attributes %s. Skipping.",
                scenario_name,
                input_attrs,
            )
            continue

        if matched_point.color == common.PredictionColor.GREY:
            # A grey cell carries no OEM prediction, so a requested point
            # landing there is almost certainly a stale selection (e.g. test
            # runs stored before the OEM re-uploaded predictions at another
            # impact location). Still selected for backwards compatibility,
            # but surfaced loudly with a pointer to the colored columns.
            non_impact_attrs = {
                key: value
                for key, value in input_attrs.items()
                if str(key).strip().lower() != "impact location"
            }
            colored_locations = sorted(
                {
                    str(tp.attributes.get("Impact location"))
                    for tp in candidate_points
                    if tp.color != common.PredictionColor.GREY
                    and _attributes_match(tp.attributes, non_impact_attrs)
                }
            )
            logger.warning(
                "[ACC %s] Selected test point %s has no OEM prediction (grey); "
                "colored predictions exist at impact location(s): %s. "
                "The stored selection may be stale.",
                scenario_name,
                input_attrs,
                ", ".join(colored_locations) if colored_locations else "none",
            )

        for key, value in input_attrs.items():
            # Alias-aware: an input spelled "Impact Location" must neither be
            # added next to the point's existing "Impact location" (duplicate
            # column in the verification sheet) nor survive under the
            # non-canonical spelling when the point lacks the key.
            target_key = ca_test_info.canonical_attribute_key(
                matched_point.attributes, key
            )
            if target_key not in matched_point.attributes:
                matched_point.attributes[target_key] = value

        selected_points.append(matched_point)

    return selected_points


def build_verification_report_df(
    verification_df: pd.DataFrame,
    acc_type_of_system: str,
) -> pd.DataFrame:
    # Split the self-describing verification_df into the block and test-point rows.
    block_categories = {"Road features", "Auto-resume"}
    category_col = (
        verification_df.get("Category", pd.Series(dtype=str)).fillna("").astype(str)
    )
    block_mask = category_col.str.strip().isin(block_categories)

    block_df = verification_df[block_mask].copy()
    test_df = verification_df[~block_mask].copy()

    # Update auto-resume type in case caller passes a different system type
    # (keeps the signature backward-compatible with existing callers).
    auto_resume_mask = block_df["Category"].str.strip() == "Auto-resume"
    block_df.loc[auto_resume_mask, "Scenario"] = acc_type_of_system

    verif_col_list = list(verification_df.columns)
    n_cols = len(verif_col_list)

    acc_road_aligned_df = pd.DataFrame("", index=block_df.index, columns=verif_col_list)
    for col_name in ["Category", "Scenario", "Value"]:
        if col_name in block_df.columns:
            acc_road_aligned_df[col_name] = block_df[col_name].fillna("").values

    verif_data = test_df.values
    empty_row = np.full((1, n_cols), "", dtype=object)
    final_df = pd.DataFrame(
        np.vstack(
            [
                acc_road_aligned_df.values,
                empty_row,
                np.array([verif_col_list]),
                verif_data,
            ]
        )
    )

    top_header_col_names = [""] * n_cols
    for col_name in ["Category", "Scenario", "Value"]:
        if col_name in verif_col_list:
            top_header_col_names[verif_col_list.index(col_name)] = col_name
    final_df.columns = top_header_col_names

    return common.opposite_ffill(
        final_df, exclude_columns=final_df.columns.difference(["Category"])
    )


def preprocess(
    dfs: dict[str, pd.DataFrame], input_selected_points: dict | None = None
) -> Dict:
    common.validate_input_selected_points(input_selected_points, context="ACC")
    logger.info("Preprocess ACC performance ...")

    acc_prediction_df = dfs.get("VA - ACC pred.", pd.DataFrame())

    if acc_prediction_df.empty:
        logger.warning("ACC Prediction sheet is missing or empty.")
        return [], pd.DataFrame(), dfs.get("Scenario Scores", pd.DataFrame())

    acc_matrix_indices = data_model.ACC_MATRIX_INDICES
    matrices_list = list(acc_matrix_indices.keys())
    using_input_points = input_selected_points is not None

    selected_test_points = []
    for matrix_name in matrices_list:
        logger.debug(f"Processing matrix: {matrix_name}")

        matrix_test_points = matrix_processing.get_test_matrix(
            acc_prediction_df,
            matrix_name,
            ca_data_model.StageSubelementKey.LSC,
            matrix_indices_dict=acc_matrix_indices,
        )

        for tp in matrix_test_points:
            tp.attributes["Scenario"] = matrix_name

        if using_input_points:
            scenario_input_points = input_selected_points.get(matrix_name, [])
            selected_test_points.extend(
                _select_points_from_input(
                    matrix_test_points, scenario_input_points, matrix_name
                )
            )
        else:
            selected_test_points.extend(
                [
                    tp
                    for tp in matrix_test_points
                    if tp.color != common.PredictionColor.GREY
                    and tp.color != common.PredictionColor.RED
                ]
            )

    verification_rows = []
    for tp in selected_test_points:
        verification_row = {}
        verification_row["Category"] = get_category_for_scenario(
            tp.attributes.get("Scenario", "")
        )
        verification_row["Test point"] = common.format_test_point(
            tp.row + 2, tp.col + 1
        )
        for attr_name, attr_value in tp.attributes.items():
            verification_row[attr_name] = attr_value

        verification_row["OEM Prediction"] = str(tp.color.value).capitalize()
        verification_row["Expected value"] = "v_reduction"
        verification_row["Value"] = np.nan
        verification_rows.append(verification_row)

    # For the "CMRs straight" scenario,
    # randomly assign half of the rows to "front"
    # and the other half to "side" for the "Additional target" column
    cmrs_straight_rows = [
        row for row in verification_rows if row.get("Scenario") == "CMRs straight"
    ]
    n = len(cmrs_straight_rows)
    if not using_input_points:
        indices = list(range(n))
        random.shuffle(indices)
        half_n = n // 2

        for i, idx in enumerate(indices):
            if i < half_n:
                cmrs_straight_rows[idx]["Additional target"] = "front"
            else:
                cmrs_straight_rows[idx]["Additional target"] = "side"

    verification_df = pd.DataFrame(verification_rows)
    preferred_col_order = [
        "Category",
        "Scenario",
        "Test point",
        "VUT speed",
        "Target speed",
        "Impact location",
        "TTC",
        "Additional target",
        "OEM Prediction",
        "Expected value",
        "Value",
    ]
    if verification_df.empty:
        verification_df = pd.DataFrame(columns=preferred_col_order)
    else:
        ordered_cols = [
            col for col in preferred_col_order if col in verification_df.columns
        ]
        extra_cols = [col for col in verification_df.columns if col not in ordered_cols]
        verification_df = verification_df[ordered_cols + extra_cols]

    param_dict = common.create_param_dict_from_input_parameters(
        dfs.get("Input parameters", pd.DataFrame()), col="Category"
    )
    acc_type_of_system = param_dict["Auto-resume"]["Type of system"]
    logger.debug(f"ACC Type of system: {acc_type_of_system}")
    scenario_scores_df = dfs.get("Scenario Scores", pd.DataFrame())
    scenario_scores_df = update_scenario_scores_autoresume_value(
        scenario_scores_df, acc_type_of_system
    )

    # Prepend road-features / auto-resume block so the verification df is
    # self-describing. compute_score (and any library consumer) can locate the
    # block by filtering Category instead of relying on row indices.
    road_features_rows = [
        {"Category": "Road features", "Scenario": "Curves", "Value": np.nan},
        {"Category": "Road features", "Scenario": "Roundabouts", "Value": np.nan},
        {
            "Category": "Road features",
            "Scenario": "Intersection (no right-of-way)",
            "Value": np.nan,
        },
        {"Category": "Road features", "Scenario": "Traffic lights", "Value": np.nan},
        {"Category": "Road features", "Scenario": "Stop signs", "Value": np.nan},
        {"Category": "Auto-resume", "Scenario": acc_type_of_system, "Value": np.nan},
    ]
    road_features_df = pd.DataFrame(road_features_rows)
    # Align columns with verification_df (fill missing cols with empty string)
    for col in verification_df.columns:
        if col not in road_features_df.columns:
            road_features_df[col] = ""
    road_features_df = road_features_df[verification_df.columns]
    verification_df = pd.concat([road_features_df, verification_df], ignore_index=True)

    logger.info(
        f"Generated ACC Verification dataframe with {len(verification_df)} rows "
        f"(including {len(road_features_rows)} road-features/auto-resume rows)."
    )
    return selected_test_points, verification_df, scenario_scores_df


def compute_score(dfs: dict[str, pd.DataFrame]) -> Dict:
    acc_score_dict = {}
    matrix_test_keys = [
        # Car-to-Car - Longitudinal
        "CCRs straight",
        "CCRs curved",
        "CCRm",
        "CCRb",
        # Car-to-Car - Cut-in/Cut-out
        "CCR cut-in",
        "CCR cut-out",
        # Car-to-Motorcyclist - Longitudinal
        "CMRs straight",
        "CMRs curved",
        "CMRm",
        "CMRb",
        # Car-to-Motorcyclist - Cut-in/Cut-out
        "CMR cut-in",
        "CMR cut-out",
        # Car-to-VRU - Longitudinal
        "CPLA",
        "CBLA",
    ]
    # NaN means "not yet assessed by the OEM" -- distinct from an explicit
    # FAIL (0.0). A matrix scenario has rows in "VA - ACC verif." only for
    # test points preprocess selects (Grey and Red cells are dropped), so the
    # accumulator is flipped to a real 0.0 either in the loop below, the
    # first time a row for the scenario is processed, or right here for a
    # scenario whose matrix the OEM did assess but colored Red everywhere:
    # that produces no verification rows at all, yet it is an explicit FAIL
    # worth 0.0, not "not assessed". Only an all-Grey matrix stays NaN.
    #
    # The matrix colours are read from both shapes the prediction sheet can
    # have (see common.merge_prediction_color_sources): the OEM's typed colour
    # words in the text frame, or -- in the preprocessed workbook that
    # compute-score actually runs on, where preprocess has re-encoded every
    # word as a cell fill and blanked the text -- the "(bg)" fill frame.
    # Matrix positions and row/column labels always come from the text frame,
    # which is the only one carrying them.
    for key in matrix_test_keys:
        acc_score_dict[key] = np.nan

    acc_prediction_df = dfs.get("VA - ACC pred.", pd.DataFrame())
    if acc_prediction_df is not None and not acc_prediction_df.empty:
        acc_prediction_color_df = common.merge_prediction_color_sources(
            acc_prediction_df, dfs.get("VA - ACC pred. (bg)")
        )
        for matrix_name in matrix_test_keys:
            matrix_indices = matrix_processing.get_matrix_indices(
                acc_prediction_df, matrix_name, data_model.ACC_MATRIX_INDICES
            )
            if not matrix_indices:
                continue
            matrix_test_points = matrix_processing.get_test_matrix_from_region(
                acc_prediction_color_df,
                matrix_indices["start_row"],
                matrix_indices["n_rows"],
                matrix_indices["start_col"],
                matrix_indices["n_cols"],
                test_name=matrix_name,
                stage_subelement_key=ca_data_model.StageSubelementKey.LSC,
                attributes_df=acc_prediction_df,
            )
            if not matrix_test_points:
                continue
            colored_points = [
                tp
                for tp in matrix_test_points
                if tp.color != common.PredictionColor.GREY
            ]
            if colored_points and all(
                tp.color == common.PredictionColor.RED for tp in colored_points
            ):
                logger.info(
                    "ACC scenario '%s' is predicted Red on every colored test "
                    "point; scoring it 0.0 instead of leaving it unassessed.",
                    matrix_name,
                )
                acc_score_dict[matrix_name] = 0.0

    acc_score_dict["Curves"] = np.nan
    acc_score_dict["Roundabouts"] = np.nan
    acc_score_dict["Intersection (no right-of-way)"] = np.nan
    acc_score_dict["Traffic lights"] = np.nan
    acc_score_dict["Stop signs"] = np.nan

    acc_score_dict["Auto-resume"] = np.nan

    acc_verification_df = dfs.get("VA - ACC verif.", pd.DataFrame())
    if acc_verification_df is None or acc_verification_df.empty:
        logger.warning(
            "VA - ACC verif. sheet is missing or empty, cannot compute ACC score."
        )
        return pd.DataFrame(), acc_score_dict

    acc_verification_df["Score"] = 0.0
    acc_verification_df["Color"] = ""

    # Detect block rows by Category — works regardless of row position.
    # Category is blank on every row but the first of its group (same
    # "blank means same as the row above" convention as every other sheet
    # here), so it must be forward-filled before filtering -- otherwise only
    # the first scenario of each block category (e.g. "Curves" under Road
    # features) is ever recognised, and every other scenario in the same
    # block (Roundabouts, Intersection, ...) is silently dropped instead of
    # scored.
    block_categories = {"Road features", "Auto-resume"}
    category_col = (
        acc_verification_df.get("Category", pd.Series(dtype=str))
        .replace("", pd.NA)
        .ffill()
        .fillna("")
        .astype(str)
    )
    block_mask = category_col.str.strip().isin(block_categories)
    # Road features/Auto-resume rows default to unassessed (NaN), not 0 --
    # only overwritten explicitly once a row is actually PASS/FAIL below.
    acc_verification_df.loc[block_mask, "Score"] = np.nan
    acc_from_prediction_df = acc_verification_df[~block_mask]

    road_features_df = acc_verification_df[category_col.str.strip() == "Road features"]
    auto_resume_df = acc_verification_df[category_col.str.strip() == "Auto-resume"]

    logger.debug(f"Road features df :\n{road_features_df}")
    logger.debug(f"Auto-resume df :\n{auto_resume_df}")
    logger.debug(
        f"ACC from prediction dataframe columns: {acc_from_prediction_df.columns.tolist()}"
    )
    logger.debug(f"ACC from prediction df :\n{acc_from_prediction_df}")
    # Matrix test score computation
    for index, row in acc_from_prediction_df.iterrows():
        scenario = row.get("Scenario", "")
        row_element = list(row.values)[1] if len(row.values) > 1 else None
        logger.debug(
            f"Processing row {index} with scenario: {scenario} and element: {row_element}"
        )
        if pd.isna(scenario) or scenario == "":
            continue

        if scenario in matrix_test_keys:
            # A row exists at all only because the OEM colored this test
            # point during preprocessing -- switch from unassessed (NaN) to
            # a real accumulator now that there's something to sum.
            if pd.isna(acc_score_dict[scenario]):
                acc_score_dict[scenario] = 0.0

            current_color = str(
                row.get(
                    "OEM Prediction", common.PredictionColor.GREY.value.capitalize()
                )
            ).strip()

            current_number_of_rows = data_model.ACC_MATRIX_INDICES.get(
                scenario, {}
            ).get("n_rows", 0)
            possible_score = (
                1.0 / current_number_of_rows if current_number_of_rows > 0 else 0
            )
            if scenario in ["CMR cut-in", "CMR cut-out"]:
                possible_score = 0.5 * possible_score

            half_score = possible_score / 2

            # No measured v_reduction yet (test point colored, but the assessor/OEM
            # hasn't filled in the Value cell) -- inherit the OEM prediction
            # color directly, weighted the same as a matching measured result,
            # rather than defaulting v_reduction to 0 (indistinguishable from a
            # real 0 km/h reduction measurement).
            if pd.isna(row.get("Value")):
                if current_color.lower() == "green":
                    score = possible_score
                elif current_color.lower() == "orange":
                    score = half_score
                else:
                    score = 0.0
                acc_score_dict[scenario] += score
                acc_verification_df.at[index, "Color"] = current_color.capitalize()
                acc_verification_df.at[index, "Score"] = score
                continue

            v_reduction_raw = row.get("Value", 0)
            v_reduction = pd.to_numeric(v_reduction_raw, errors="coerce")
            if pd.isna(v_reduction):
                logger.warning(
                    f"Could not parse numeric v_reduction from '{v_reduction_raw}' for scenario '{scenario}'; score defaults to 0 unless other criteria are met."
                )

            vut_speed_raw = row.get("VUT speed", 0)

            v_scenario = None
            if pd.notna(vut_speed_raw):
                match = re.search(r"(\d+)", str(vut_speed_raw))
                if match:
                    v_scenario = int(match.group(1))

            if v_scenario is None:
                logger.warning(
                    f"Could not parse VUT speed from '{vut_speed_raw}' for scenario '{scenario}'; forcing score to 0 for this row."
                )
                acc_verification_df.at[index, "Color"] = (
                    common.PredictionColor.RED.value.capitalize()
                )
                acc_verification_df.at[index, "Score"] = 0
                continue

            target_speed_raw = row.get("Target speed", 0)
            v_target = 0
            if pd.notna(target_speed_raw):
                match_target = re.search(r"(\d+)", str(target_speed_raw))
                if match_target:
                    v_target = int(match_target.group(1))

            logger.debug(
                f"Scenario: {scenario}, VUT speed: {v_scenario}, Target speed: {v_target}, Prediction color: {current_color}, Value (v_reduction): {v_reduction}, Number of rows in matrix: {current_number_of_rows}"
            )
            # Scoring based on v_reduction criteria. The green-result
            # threshold depends on the scenario group:
            # - Car-to-VRU - Longitudinal (CPLA/CBLA): fixed 30 km/h
            # - Car (CCR*) / PTW (CMR*): v_scenario - v_target - 2
            # GREEN: v_reduction > green_threshold => full score
            #        v_reduction > 15 => half score
            #        else => 0
            # ORANGE: v_reduction > 15 => half score; else => 0
            # An exact tie (v_reduction == green_threshold) lands in the
            # orange band (protocol: orange is "> 15", green bound strict),
            # matching the Orange-prediction branch below.
            green_threshold = get_green_v_reduction_threshold(
                scenario, v_scenario, v_target
            )
            if current_color.lower() == "green":
                if v_reduction > green_threshold:
                    acc_score_dict[scenario] += possible_score
                    acc_verification_df.at[index, "Color"] = (
                        common.PredictionColor.GREEN.value.capitalize()
                    )
                    acc_verification_df.at[index, "Score"] = possible_score
                elif v_reduction > ORANGE_V_REDUCTION_THRESHOLD:
                    acc_score_dict[scenario] += half_score
                    acc_verification_df.at[index, "Color"] = (
                        common.PredictionColor.ORANGE.value.capitalize()
                    )
                    acc_verification_df.at[index, "Score"] = half_score
                else:
                    acc_score_dict[scenario] += 0
                    acc_verification_df.at[index, "Color"] = (
                        common.PredictionColor.RED.value.capitalize()
                    )
                    acc_verification_df.at[index, "Score"] = 0

            # Orange prediction: if the test result meets the green threshold,
            # award full score (ENCAP WG decision: orange prediction + green result = full score).
            # v_reduction > green_threshold => full score (green result)
            # v_reduction > 15 => half score (orange result)
            # else => 0
            elif current_color.lower() == "orange":
                if v_reduction > green_threshold:
                    acc_score_dict[scenario] += possible_score
                    acc_verification_df.at[index, "Color"] = (
                        common.PredictionColor.GREEN.value.capitalize()
                    )
                    acc_verification_df.at[index, "Score"] = possible_score
                elif v_reduction > ORANGE_V_REDUCTION_THRESHOLD:
                    acc_score_dict[scenario] += half_score
                    acc_verification_df.at[index, "Color"] = (
                        common.PredictionColor.ORANGE.value.capitalize()
                    )
                    acc_verification_df.at[index, "Score"] = half_score
                else:
                    acc_score_dict[scenario] += 0
                    acc_verification_df.at[index, "Color"] = (
                        common.PredictionColor.RED.value.capitalize()
                    )
                    acc_verification_df.at[index, "Score"] = 0
            else:
                acc_score_dict[scenario] += 0
                acc_verification_df.at[index, "Color"] = (
                    common.PredictionColor.RED.value.capitalize()
                )
                acc_verification_df.at[index, "Score"] = 0

    for index, row in road_features_df.iterrows():
        state = common.classify_pass_fail_value(row.get("Value"))
        if state == "blank":
            continue  # leave unassessed (NaN)
        curr_scenario = row.get("Scenario", "")
        score = 0.2 if state == "pass" else 0.0
        acc_verification_df.at[index, "Score"] = score
        if pd.isna(acc_score_dict.get(curr_scenario)):
            acc_score_dict[curr_scenario] = 0.0
        acc_score_dict[curr_scenario] += score

    for index, row in auto_resume_df.iterrows():
        if data_model.is_not_applicable(row.get("Scenario")):
            # N/A auto-resume system: scores a real 0.0 with no user input
            # required, so the blank->NaN convention below must not apply.
            acc_verification_df.at[index, "Score"] = 0.0
            if pd.isna(acc_score_dict["Auto-resume"]):
                acc_score_dict["Auto-resume"] = 0.0
            continue
        state = common.classify_pass_fail_value(row.get("Value"))
        if state == "blank":
            continue  # leave unassessed (NaN)
        auto_resume_score = 0.0
        if state == "pass":
            element = row.get("Scenario", "")
            element = str(element).strip().lower()
            if element == "automatic resume":
                auto_resume_score = 1.0
            elif element == "driver input":
                auto_resume_score = 0.5
        acc_verification_df.at[index, "Score"] = auto_resume_score
        if pd.isna(acc_score_dict["Auto-resume"]):
            acc_score_dict["Auto-resume"] = 0.0
        acc_score_dict["Auto-resume"] += auto_resume_score

    acc_verification_col_names = [
        col if "Unnamed" not in str(col) else ""
        for col in acc_verification_df.columns.tolist()
    ]
    acc_verification_df.columns = acc_verification_col_names
    # Rename column "Color" to ""
    if "Color" in acc_verification_df.columns:
        acc_verification_df.rename(columns={"Color": ""}, inplace=True)

    logger.info(f"Computed ACC scores: {acc_score_dict}")
    return acc_verification_df, acc_score_dict
